#random numbers in numpy: In NumPy, we can generate random numbers using the numpy.random module. This module provides various functions to generate random numbers from different distributions, such as uniform, normal, and binomial distributions. Random numbers are useful in simulations, statistical sampling, and various applications in data science and machine learning.

import numpy as np

rng = np.random.default_rng() #This creates a random number generator object using the default random number generator. The default_rng() function is recommended for generating random numbers in NumPy, as it provides better randomness and performance compared to the older random functions.

print(rng) #This will print the random number generator object.
print(rng.integers(1,7)) #This will generate a random integer between 1 and 6 (inclusive). The integers() function takes two arguments: the lower bound (inclusive) and the upper bound (exclusive) for the random integers to be generated.

print(rng.integers(low= 1, high= 7)) #This will generate a random integer between 1 and 6 (inclusive). The integers() function takes two arguments: the lower bound (inclusive) and the upper bound (exclusive) for the random integers to be generated. Here, we are using keyword arguments to specify the lower and upper bounds.

print(rng.integers(1,100)) #This will generate a random integer between 1 and 99 (inclusive).

#Even if we need multiple random integers, we can specify the size argument in the integers() function. For example, if we want to generate 5 random integers between 1 and 100, we can use the following code:

print(rng.integers(1,100, size=5)) #This will generate an array of 5 random integers between 1 and 99 (inclusive). The size argument specifies the number of random integers to be generated.

#Generally, it is stored in one day array. But, if we want to generate a 2D array of random integers, we can specify the size argument as a tuple. For example, if we want to generate a 3x4 array of random integers between 1 and 100, we can use the following code:

print(rng.integers(1,100, size=(3,4))) #This will generate a 3x4 array of random integers between 1 and 99 (inclusive). The size argument is specified as a tuple (3,4), indicating that we want a 2D array with 3 rows and 4 columns.

#seed: In NumPy, we can set a seed for the random number generator to ensure reproducibility of random numbers. Setting a seed allows us to generate the same sequence of random numbers every time we run the code. This is useful for debugging and testing purposes.

rng = np.random.default_rng(seed=42) #This creates a random number generator object with a seed value of 42. The seed value can be any integer, and it determines the sequence of random numbers generated by the random number generator.
print(rng.integers(1,100, size=5)) #This will generate an array of 5 random integers between 1 and 99 (inclusive). Since we have set a seed, the same sequence of random numbers will be generated every time we run the code.

#random can also be used in case of floating point numbers.

print(np.random.uniform(low = -1, high = 1))

print(np.random.uniform(low = -1, high = 1, size = 5)) #This will generate an array of 5 random floating-point numbers between -1 and 1 (inclusive). The uniform() function generates random numbers from a uniform distribution, where each number has an equal probability of being selected within the specified range.

print(np.random.uniform(-1, 1, size = (2,3)))

rng = np.random.default_rng()
array = np.array([1,2,3,4,5])

rng.shuffle(array) #This will shuffle the elements of the array in place, randomly rearranging their order. The shuffle() function modifies the original array and does not return a new array.
print(array) #This will print the shuffled array.

fruits = np.array(['apple', 'banana', 'cherry', 'litchi', 'mango'])
fruit = rng.choice(fruits) #This will randomly select one element from the fruits array. The choice() function takes an array as input and returns a randomly selected element from that array.
print(fruit)

fruit1 = rng.choice(fruits, size=3) #This will randomly select 3 elements from the fruits array. The size argument specifies the number of elements to be selected.
print(fruit1) #This will print an array of 3 randomly selected fruits from the fruits array.